#!/usr/bin/env python3
"""Tests for iris.py's _generate_daily_briefing_combined branch.

Stdlib unittest only (repo convention). Run:
    python3 tests/test_generate_briefing_combined.py
or under the suite:
    python3 -m unittest discover -s tests -v

WHY THIS EXISTS. The 2026-08-10 fix rewired _generate_daily_briefing_combined to
delegate the split to briefing_headguard.split_combined (fully mutation-covered
in test_briefing_headguard.py). But the iris.py glue line `if split is not None:`
had NO fixture, so `precheck.sh --mutate iris.py` reported three survivors there:
flip the branch either way and every suite stayed green. That branch is what
decides whether Steve's morning brief is the real PART 2 tail or a degraded
"couldn't extract" notice — not cosmetic. These two tests kill the three
survivors by exercising both arms with a stubbed query_cloud (no cloud call).

Imports the REAL iris.py via the same stub pattern as test_ceo_brief_recency.py —
a test against a re-implementation proves nothing. dotenv is force-stubbed so the
module-scope load_dotenv() never reads production credentials into the process.
"""
import asyncio
import importlib
import importlib.util
import os
import sys
import types
import unittest
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent


def _stub(name: str, force: bool = False, **attrs) -> None:
    """Register a placeholder module unless a real one is importable (see
    test_ceo_brief_recency for the full rationale). force=True stubs regardless —
    required for dotenv, whose import runs load_dotenv() at iris module scope."""
    if not force:
        try:
            importlib.import_module(name)
            return
        except Exception:
            pass
    parts = name.split(".")
    for i in range(1, len(parts) + 1):
        sub = ".".join(parts[:i])
        if sub not in sys.modules:
            sys.modules[sub] = types.ModuleType(sub)
    for k, v in attrs.items():
        setattr(sys.modules[name], k, v)


def _load_iris():
    _stub("apscheduler.schedulers.asyncio", AsyncIOScheduler=object)
    _stub("apscheduler.triggers.cron", CronTrigger=object)
    _stub("apscheduler.triggers.interval", IntervalTrigger=object)
    _stub("dotenv", force=True, load_dotenv=lambda *a, **k: None)
    _stub("telegram", Update=object)
    _stub("telegram.error", NetworkError=Exception, RetryAfter=Exception,
          TimedOut=Exception)
    _stub("telegram.ext", Application=object, ContextTypes=object,
          MessageHandler=object, filters=object)
    sdk = types.ModuleType("claude_agent_sdk")
    for attr in ("ClaudeSDKClient", "ClaudeAgentOptions", "AssistantMessage",
                 "TextBlock", "ResultMessage", "ToolUseBlock", "ToolResultBlock",
                 "UserMessage", "SystemMessage"):
        setattr(sdk, attr, type(attr, (), {}))
    sdk.tool = lambda *a, **k: (lambda fn: fn)
    sdk.query = lambda *a, **k: None
    sdk.create_sdk_mcp_server = lambda *a, **k: None
    sys.modules.setdefault("claude_agent_sdk", sdk)
    os.environ.setdefault("TELEGRAM_BOT_TOKEN", "test-token-not-a-real-credential")

    spec = importlib.util.spec_from_file_location("iris_under_test", REPO / "iris.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


iris = _load_iris()

FILE_HALF = (
    "# Daily Briefing — 2026-08-30 (Saturday)\n\n"
    "_Auto-generated by Iris daemon scheduled job._\n\n"
    "## Today's Focus\n\nV14 is the lever today.\n"
)
BRIEF_HALF = "Good morning Steve. V14 ships today. — Iris"


class TestGenerateDailyBriefingCombined(unittest.TestCase):
    """The branch that decides real-brief vs degraded-notice. Kills the three
    iris.py:3835 `if split is not None:` survivors."""

    def _run_with_output(self, out: str):
        """Stub query_cloud to return `out`, run the coroutine, restore."""
        original = iris.query_cloud

        async def _fake_query_cloud(prompt, history, timeout=None, **kwargs):
            return out

        iris.query_cloud = _fake_query_cloud
        try:
            return asyncio.run(iris._generate_daily_briefing_combined())
        finally:
            iris.query_cloud = original

    def test_boundary_present_returns_real_split(self):
        # split_combined finds a boundary -> the not-None arm returns (file, brief).
        out = f"{FILE_HALF}\n{iris.BRIEFING_SENTINEL}\n{BRIEF_HALF}"
        file_md, brief = self._run_with_output(out)
        self.assertIn("# Daily Briefing", file_md)
        self.assertEqual(brief, BRIEF_HALF)
        # The regression that mattered: the brief is the TAIL, never the file head.
        self.assertNotIn("Today's Focus", brief)

    def test_part2_heading_substituted_for_sentinel(self):
        # The real failure shape (7/20-8/10): model emits a '# PART 2' heading
        # instead of the bare sentinel. Still a boundary -> real brief extracted.
        out = (
            f"{FILE_HALF}\n"
            "# PART 2 — the Telegram brief\n\n"
            f"{BRIEF_HALF}"
        )
        file_md, brief = self._run_with_output(out)
        self.assertIn("# Daily Briefing", file_md)
        self.assertEqual(brief, BRIEF_HALF)

    def test_no_boundary_returns_degraded_notice(self):
        # split_combined returns None -> the None arm returns (out, warning). If
        # the branch were forced True it would unpack None and raise; forced False
        # is this arm. Either mutant diverges from this expected tuple.
        out = "I'll generate both outputs.\n" + FILE_HALF  # no sentinel, no PART 2
        file_md, brief = self._run_with_output(out)
        self.assertEqual(file_md, out.strip())
        self.assertTrue(brief.startswith("⚠️ Morning briefing could not be extracted"))


if __name__ == "__main__":
    unittest.main(verbosity=2)
