#!/usr/bin/env python3
"""build_mocs.py — connect orphan notes in the 3SK/Iris vault into the Obsidian graph.

The "brain" graph shows isolated dots: notes with no [[wikilink]] in or out. These
are real production artifacts (video scripts, packaging, intel, adaptations, ebook
products) that agents emit but never get linked. This tool adopts every orphan into
a hub note so it becomes connected and navigable:

  - 3SK Finance video artifacts  ->  per-video hub   BRANDS/3SK_Finance/_Video_Hubs/Video_NN.md
  - everything else              ->  per-folder MOC  <folder>/_<Leaf>_MOC.md

All generated hubs are linked from a managed block in _MAP/Vault_MOC.md, so the hubs
are themselves connected to the front-page map (no new orphans created).

SAFETY: only ever CREATES/overwrites auto-managed hub files (each stamped with
AUTO_MARKER) and replaces one clearly-delimited managed block in Vault_MOC.md. It
NEVER edits, deletes, moves, or renames any source artifact. Idempotent: re-running
regenerates the auto files in place. Designed to run nightly from the vault gardener.

Usage:
  build_mocs.py [--vault PATH] [--dry-run] [--quiet]
"""
from __future__ import annotations

import argparse
import os
import re
import sys
from collections import defaultdict
from urllib.parse import unquote

DEFAULT_VAULT = "/Users/steve/Documents/3SK/outputs"

AUTO_MARKER = "<!-- AUTO-MOC: generated by scripts/build_mocs.py — do not edit by hand -->"
BLOCK_BEGIN = "<!-- AUTO-MOC:BEGIN (generated by scripts/build_mocs.py — do not edit) -->"
BLOCK_END = "<!-- AUTO-MOC:END -->"

# Directories never scanned or written (hygiene + data-loss safety contract).
# `outputs` is a hard floor: the business vault is nested inside the second-brain
# root, so if this script is ever pointed at the root it must NOT descend into the
# business vault and scatter wrong-base MOCs there (it has its own librarian pass).
SKIP_DIRS = {".obsidian", ".git", ".trash", "07_Archive", "__pycache__", "node_modules", "outputs"}

# Top-level instruction/config notes that are not vault "content" — leave un-adopted.
EXCLUDE_NAMES = {"CLAUDE.md", "CLAUDE_PROJECT_INSTRUCTIONS.md"}

WIKILINK = re.compile(r"!?\[\[([^\]]+)\]\]")
MDLINK = re.compile(r"\]\(([^)]+?\.md)(?:#[^)]*)?\)")
FM_VIDEO = re.compile(r"^video[-_]?:\s*[\"']?([^\"'\n]+)", re.IGNORECASE | re.MULTILINE)
FM_TITLE = re.compile(r"^title:\s*[\"']?([^\"'\n]+)", re.IGNORECASE | re.MULTILINE)
VIDEO_NUM = re.compile(r"(?:video[_\-\s]?|^)0*(\d+)", re.IGNORECASE)
FNAME_VIDEO = re.compile(r"Video[_\-]?0*(\d+)", re.IGNORECASE)

FINANCE_ROOT = os.path.join("BRANDS", "3SK_Finance")


def warn(msg: str) -> None:
    print(f"build_mocs: WARNING: {msg}", file=sys.stderr)


def is_auto_file(relpath: str, text: str | None) -> bool:
    """True ONLY for files this script generated, fingerprinted by AUTO_MARKER as the
    FIRST line (the generator always emits it as line 1).

    Deliberately NOT a substring check and NEVER a filename check: a substring check
    would treat a human doc that merely *quotes* the marker (e.g. a design/review note
    about this script) as auto — and that file could then be overwritten or pruned. A
    filename check would misclassify the human master MOC (Vault_MOC.md). Requiring the
    marker on line 1 is a structural signature a prose doc can't satisfy by accident."""
    if not text:
        return False
    stripped = text.lstrip()
    return bool(stripped) and stripped.splitlines()[0].strip() == AUTO_MARKER


def removable_auto(relpath: str, text: str | None) -> bool:
    """Stale auto-file safe to prune: carries our marker AND lives where we put hubs.
    Double-gated so nothing user-authored can ever match."""
    if not is_auto_file(relpath, text):
        return False
    name = os.path.basename(relpath)
    return name.endswith("_MOC.md") or f"{os.sep}_Video_Hubs{os.sep}" in f"{os.sep}{relpath}"


def is_hub_file(relpath: str) -> bool:
    """Human-maintained navigation notes — skip as orphan members (navigation, not content)."""
    return os.path.basename(relpath) in ("README.md", "_index.md", "Vault_MOC.md", "File_Index.md")


def safe_write(vault: str, rel: str, content: str, dry: bool) -> bool:
    """Write an auto-managed hub file. REFUSES to overwrite any file that is not one of
    OUR auto files (strict first-line fingerprint via is_auto_file — a human note that
    merely quotes the marker is NOT auto), so a human-authored note can never be
    clobbered. Warns (never raises) on I/O error."""
    path = os.path.join(vault, rel)
    if os.path.exists(path):
        existing = read(vault, rel)
        if not is_auto_file(rel, existing):
            warn(f"refusing to overwrite non-auto file: {rel}")
            return False
    if dry:
        return True
    try:
        os.makedirs(os.path.dirname(path) or vault, exist_ok=True)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)
        return True
    except OSError as e:
        warn(f"write failed for {rel}: {e}")
        return False


def list_notes(vault: str) -> list[str]:
    notes = []
    for dp, dn, fn in os.walk(vault):
        dn[:] = [d for d in dn if d not in SKIP_DIRS and not d.startswith(".")]
        for f in fn:
            if f.endswith(".md"):
                notes.append(os.path.relpath(os.path.join(dp, f), vault))
    return sorted(notes)


def read(vault: str, rel: str) -> str:
    try:
        with open(os.path.join(vault, rel), encoding="utf-8", errors="ignore") as fh:
            return fh.read()
    except OSError:
        return ""


def build_link_graph(vault: str, notes: list[str], texts: dict[str, str], auto: set[str]):
    """Resolve every wikilink/md-link to a target note. Returns (out_links, in_links).

    Auto-generated hub files are excluded as link *sources*: their links must not
    "rescue" an orphan, or adoption would collapse on the next run (idempotency)."""
    by_base: dict[str, list[str]] = defaultdict(list)
    by_relstem: dict[str, str] = {}
    for rel in notes:
        stem = rel[:-3] if rel.endswith(".md") else rel
        by_relstem[stem.lower()] = rel
        by_relstem[rel.lower()] = rel
        by_base[os.path.splitext(os.path.basename(rel))[0].lower()].append(rel)

    out_links: dict[str, set[str]] = defaultdict(set)
    in_links: dict[str, set[str]] = defaultdict(set)

    def resolve(target: str, src: str) -> str | None:
        target = unquote(target.split("|")[0].split("#")[0]).strip().lstrip("./").strip()
        if not target:
            return None
        key = target.lower()
        keymd = key if key.endswith(".md") else key + ".md"
        # 1) exact relative-path match
        if key in by_relstem:
            return by_relstem[key]
        if keymd[:-3] in by_relstem:
            return by_relstem[keymd[:-3]]
        # 2) unique basename match
        base = os.path.splitext(os.path.basename(target))[0].lower()
        cands = by_base.get(base, [])
        if len(cands) == 1:
            return cands[0]
        if len(cands) > 1:
            # ambiguous: prefer a candidate in the same folder as the source
            srcdir = os.path.dirname(src)
            same = [c for c in cands if os.path.dirname(c) == srcdir]
            if len(same) == 1:
                return same[0]
            return None  # genuinely ambiguous — don't credit a random file
        return None

    for rel in notes:
        if rel in auto:
            continue
        txt = texts[rel]
        targets = set()
        for m in WIKILINK.finditer(txt):
            targets.add(m.group(1))
        for m in MDLINK.finditer(txt):
            targets.add(m.group(1))
        for t in targets:
            r = resolve(t, rel)
            if r and r != rel:
                out_links[rel].add(r)
                in_links[r].add(rel)
    return out_links, in_links


def video_number_for(vault: str, rel: str, text: str) -> str | None:
    """Return a 2-digit video number for a 3SK Finance artifact, or None."""
    if not rel.startswith(FINANCE_ROOT + os.sep):
        return None
    fm = text.split("---", 2)
    frontmatter = fm[1] if text.lstrip().startswith("---") and len(fm) >= 3 else ""
    m = FM_VIDEO.search(frontmatter)
    if m:
        vm = VIDEO_NUM.search(m.group(1))
        if vm:
            return f"{int(vm.group(1)):02d}"
    fn = FNAME_VIDEO.search(os.path.basename(rel))
    if fn:
        return f"{int(fn.group(1)):02d}"
    return None


def video_title_for(vault: str, rels: list[str], texts: dict[str, str]) -> str:
    """Best-effort human title for a video hub, preferring the Script note's frontmatter."""
    scripts = [r for r in rels if "Script" in os.path.basename(r)] or rels
    for r in scripts:
        m = FM_TITLE.search(texts[r])
        if m and m.group(1).strip():
            return m.group(1).strip()
    return ""


def wikilink(rel: str, alias: str | None = None) -> str:
    """Full-path wikilink with an alias — robust against duplicate basenames."""
    stem = rel[:-3] if rel.endswith(".md") else rel
    return f"[[{stem}|{alias or os.path.basename(stem)}]]"


def title_case(name: str) -> str:
    return name.replace("_", " ").replace("-", " ").strip()


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--vault", default=DEFAULT_VAULT)
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--quiet", action="store_true", help="only print on changes/errors")
    args = ap.parse_args()

    vault = os.path.abspath(args.vault)
    if not os.path.isdir(vault):
        print(f"ERROR: vault not found: {vault}", file=sys.stderr)
        return 1

    notes = list_notes(vault)
    texts = {rel: read(vault, rel) for rel in notes}

    auto = {rel for rel in notes if is_auto_file(rel, texts[rel])}
    # Strip the auto-maintained block from the master MOC before detection, so links
    # this script itself injects there never "rescue" an orphan (idempotency).
    graph_texts = dict(texts)
    moc_rel = os.path.join("_MAP", "Vault_MOC.md")
    if moc_rel in graph_texts:
        graph_texts[moc_rel] = re.sub(
            re.escape(BLOCK_BEGIN) + r".*?" + re.escape(BLOCK_END), "",
            graph_texts[moc_rel], flags=re.DOTALL)
    out_links, in_links = build_link_graph(vault, notes, graph_texts, auto)

    # Orphans = content notes with no edge in either direction.
    orphans = []
    for rel in notes:
        if is_auto_file(rel, texts[rel]):
            continue
        if os.path.basename(rel) in EXCLUDE_NAMES:
            continue
        if not out_links[rel] and not in_links[rel]:
            orphans.append(rel)

    # Assign each orphan to a hub.
    video_hubs: dict[str, list[str]] = defaultdict(list)   # "NN" -> [rels]
    folder_mocs: dict[str, list[str]] = defaultdict(list)  # dir  -> [rels]
    readme_orphans: list[str] = []                         # folder guides -> master block
    for rel in orphans:
        if os.path.basename(rel) in ("README.md", "_index.md"):
            readme_orphans.append(rel)  # connected via the master MOC "Folder guides" list
            continue
        vn = video_number_for(vault, rel, texts[rel])
        if vn:
            video_hubs[vn].append(rel)
        else:
            folder_mocs[os.path.dirname(rel)].append(rel)

    # --- generate per-video hubs ---
    gen_video: list[str] = []   # relpaths of video-hub files
    gen_folder: list[str] = []  # relpaths of folder-MOC files
    video_hub_dir = os.path.join(FINANCE_ROOT, "_Video_Hubs")
    for vn in sorted(video_hubs):
        members = sorted(video_hubs[vn])
        title = video_title_for(vault, members, texts)
        rel_hub = os.path.join(video_hub_dir, f"Video_{vn}.md")
        # group members by their leaf folder for readability
        by_kind: dict[str, list[str]] = defaultdict(list)
        for m in members:
            by_kind[os.path.basename(os.path.dirname(m))].append(m)
        lines = [
            AUTO_MARKER,
            "---",
            "type: video-hub",
            "brand: 3SK_Finance",
            f'video: "{vn}"',
            "maintained-by: build_mocs.py",
            "tags:",
            "  - meta/moc",
            "  - production/video-hub",
            "---",
            "",
            f"# Video {vn} — Hub" + (f": {title}" if title else ""),
            "",
            f"All production artifacts for 3SK Finance Video {vn}, auto-linked so they form a "
            "connected cluster in the graph. Regenerated nightly by `build_mocs.py`.",
            "",
        ]
        for kind in sorted(by_kind):
            lines.append(f"## {title_case(kind)}")
            for m in sorted(by_kind[kind]):
                lines.append(f"- {wikilink(m)}")
            lines.append("")
        lines.append("_Linked from [[_MAP/Vault_MOC|Vault MOC]]._")
        content = "\n".join(lines).rstrip() + "\n"
        if safe_write(vault, rel_hub, content, args.dry_run):
            gen_video.append(rel_hub)

    # --- generate per-folder MOCs ---
    for folder in sorted(folder_mocs):
        # list ALL non-hub, non-auto content notes in this folder (true folder index),
        # so the MOC is genuinely useful and every orphan here is covered.
        members = sorted(
            r for r in notes
            if os.path.dirname(r) == folder
            and not is_hub_file(r)
            and not is_auto_file(r, texts[r])
            and os.path.basename(r) not in EXCLUDE_NAMES
        )
        if not members:
            continue
        leaf = os.path.basename(folder) or "Root"
        rel_moc = os.path.join(folder, f"_{leaf}_MOC.md")
        lines = [
            AUTO_MARKER,
            "---",
            "type: folder-moc",
            "maintained-by: build_mocs.py",
            "tags:",
            "  - meta/moc",
            "---",
            "",
            f"# {title_case(leaf)} — Index",
            "",
            f"Auto-generated index of every note in `{folder}/`, so nothing here floats "
            "unconnected in the graph. Regenerated nightly by `build_mocs.py`.",
            "",
        ]
        for m in members:
            lines.append(f"- {wikilink(m)}")
        lines.append("")
        lines.append("_Linked from [[_MAP/Vault_MOC|Vault MOC]]._")
        content = "\n".join(lines).rstrip() + "\n"
        if safe_write(vault, rel_moc, content, args.dry_run):
            gen_folder.append(rel_moc)

    generated = gen_video + gen_folder

    # --- prune STALE auto-files (folders that lost all orphans, renamed hubs, etc.) ---
    # Without this, a no-longer-regenerated hub stays on disk, drops out of the master
    # block, and becomes a permanent orphan — the very problem this tool fixes. Strictly
    # marker-gated + name-gated (removable_auto) so only our own regenerable output can
    # ever match; skipped entirely if we generated nothing (a safety circuit-breaker).
    #
    # NEVER os.remove: the vault is NOT git-tracked and IS Drive-synced (2026-05-27
    # data-loss history), so destroying a file outright is unrecoverable if our gating
    # were ever wrong. Instead RENAME to a sibling `.bak` — this still removes the `.md`
    # node from the Obsidian graph (the goal) while preserving the content on disk. A
    # prior `.bak` is replaced (os.replace is atomic); only our own regenerable hubs are
    # ever touched, so the churn of stale .bak files is bounded and recoverable.
    pruned: list[str] = []
    generated_set = set(generated)
    if generated:
        for rel in notes:
            if rel not in generated_set and removable_auto(rel, texts[rel]):
                if args.dry_run:
                    pruned.append(rel)
                else:
                    src = os.path.join(vault, rel)
                    try:
                        os.replace(src, src + ".bak")
                        pruned.append(rel)
                    except OSError as e:
                        warn(f"could not prune stale auto-file {rel}: {e}")

    # --- wire all hubs into the master MOC via a managed block ---
    moc_path = os.path.join(vault, moc_rel)
    block_lines = [BLOCK_BEGIN, "", "## 🔗 Connected clusters (auto-maintained)", ""]
    if gen_video:
        block_lines.append("**3SK Finance video hubs:** "
                           + " · ".join(wikilink(p) for p in sorted(gen_video)))
        block_lines.append("")
    if gen_folder:
        block_lines.append("**Folder indexes:**")
        for p in sorted(gen_folder):
            block_lines.append(f"- {wikilink(p)}")
        block_lines.append("")
    if readme_orphans:
        block_lines.append("**Folder guides:**")
        for p in sorted(readme_orphans):
            label = os.path.basename(os.path.dirname(p)) or "Vault root"
            block_lines.append(f"- {wikilink(p, label)}")
        block_lines.append("")
    block_lines.append(BLOCK_END)
    block = "\n".join(block_lines)

    moc_changed = False
    if os.path.isfile(moc_path):
        moc_txt = read(vault, moc_rel)
        if BLOCK_BEGIN in moc_txt and BLOCK_END in moc_txt:
            new_txt = re.sub(
                re.escape(BLOCK_BEGIN) + r".*?" + re.escape(BLOCK_END),
                block,
                moc_txt,
                count=1,
                flags=re.DOTALL,
            )
        else:
            new_txt = moc_txt.rstrip() + "\n\n" + block + "\n"
        if new_txt != moc_txt:
            moc_changed = True
            if not args.dry_run:
                try:
                    with open(moc_path, "w", encoding="utf-8") as fh:
                        fh.write(new_txt)
                except OSError as e:
                    moc_changed = False
                    warn(f"could not update master MOC {moc_rel}: {e}")
    else:
        warn(f"master MOC not found at {moc_rel}; hubs generated but not linked.")

    # --- report ---
    n_orphans = len(orphans)
    if not (args.quiet and n_orphans == 0 and not moc_changed and not pruned):
        mode = "DRY-RUN " if args.dry_run else ""
        print(f"{mode}build_mocs: {n_orphans} orphan(s) adopted -> "
              f"{len(video_hubs)} video hub(s) + {len(folder_mocs)} folder index(es); "
              f"{len(pruned)} stale hub(s) pruned; "
              f"master MOC {'updated' if moc_changed else 'unchanged'}.")
        if args.dry_run or not args.quiet:
            for vn in sorted(video_hubs):
                print(f"  video {vn}: {len(video_hubs[vn])} file(s)")
            for folder in sorted(folder_mocs):
                print(f"  {folder}/: {len(folder_mocs[folder])} orphan(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
