#!/usr/bin/env python3
"""overnight_selfcheck.py — v1.3 (2026-07-23)

Deterministic local verification that the overnight jobs ran. Judges by real
on-disk evidence — file mtimes for artifacts, and the wrapper's own
"completed ok" sentinel for jobs — never by a schedule label (see the 7/22
fire-time defect). ⚠️ Do NOT "simplify" either job leg back to a log mtime:
run_claude_job.sh appends to its log on EVERY outcome, so an mtime check
reports green on a night the job ran and failed. That is a real regression
that shipped in v1.2 and was caught at review; see _SENTINEL.

Writes .activity/heartbeat.json atomically and pushes it to Drive, where the
07:15 ET cloud watchdog reads it.

Exit 0 = all green, 1 = anomaly (or Drive push failed), 2 = self-error.
Non-zero also pings Telegram — Steve's canonical alert channel — because
nothing else consumes this job's exit code.

Run via launchd at 06:55 ET daily (com.iris.selfcheck).
Read-only except heartbeat.json. Never deletes anything.
`--selftest` runs the date-logic checks and exits.

⚠️  CLOUD WATCHDOG CONTRACT: if a push fails, Drive keeps YESTERDAY's
heartbeat.json — and a stale `all_green: true` would certify a machine that
has been dark for a day. So a dated copy, heartbeat-YYYY-MM-DD.json, is
pushed alongside it: "today's dated file is absent" is unambiguous to any
reader and needs no discipline from the watchdog. Preferred check is the
dated file; reading heartbeat.json is only safe if the reader rejects on
`date_et != today (ET)` BEFORE looking at `all_green`.

Task-0 / review corrections vs the pickup spec (each verified on disk):
  * daily_briefing: spec said "fresh within 8h (~03:45 pulse)". Wrong on both
    counts — DAILY_BRIEFING.md is regenerated by iris.py's morning brief at
    MORNING_BRIEFING_HOUR=8 (iris.py:847), so at 06:55 it is ALWAYS ~23h old
    and an 8h window would have gone ANOMALY every single day. Uses a
    directional floor (mtime >= last 08:00 - grace), matching
    prebrief_fire_check._check_morning_brief, so a late fire after a machine
    sleep doesn't invent a failure either.
  * nightly_eng: spec proposed a today-dated bridge-file entry. Dead check —
    book-update (02:30), vault-gardener (04:10) and pre-brief (05:00) all
    append today-dated entries to that same file before 06:55, so it could
    never go red. Uses the job's own single-writer wrapper log instead.
    (The spec's "KNOWN FLAKY (missed 7/19, 7/21, 7/22)" premise is also
    FALSE — those misses were a phantom from a stale cadence registry,
    closed 7/22. The job completed ok all four nights.)
  * book_update: spec watched iris-studio-ebook/ for touched files. That
    false-alarms on a legitimate "all 4 books no-op" night — a DOCUMENTED
    normal outcome that occurred 7/19 and 7/20, when the dir got zero writes
    while the job completed fine. Watches the job's wrapper log instead.
  * Both job legs parse the wrapper's "completed ok" SENTINEL, never the
    log's mtime — see _SENTINEL. An mtime check is green on a night the job
    ran and failed.
  * Drive push added: the 03:45 drive-sync mirror runs ~3h BEFORE this job,
    so a locally-written heartbeat would sit a full day and the watchdog
    would grade ~24h-stale data.

Both wrapper logs are appended by run_claude_job.sh on every run including
no-op runs (verified 7/19-7/22), and each has exactly one writer — which is
what makes them trustworthy evidence where the shared bridge file is not.
"""
import argparse
import json
import os
import re
import socket
import subprocess
import sys
import tempfile
import time
from datetime import datetime, timedelta, timezone
from pathlib import Path
from zoneinfo import ZoneInfo

# ---- config (verified on disk 2026-07-22) ------------------------------------
VAULT = Path("/Users/steve/Documents/3SK/outputs")
LOGS = Path("/Users/steve/iris_studio/logs")
ET = ZoneInfo("America/New_York")
HEARTBEAT = VAULT / "_Iris_Memory" / "Daily" / ".activity" / "heartbeat.json"
NOTIFY = "/Volumes/AI_Workspace/iris_studio/scripts/notify.sh"

# Mirrors iris.py:847. If the morning brief moves, this moves.
MORNING_BRIEFING_HOUR = 8
BRIEFING_GRACE = timedelta(hours=2)

# Single-file push so the watchdog reads today's heartbeat, not yesterday's.
RCLONE = "/opt/homebrew/bin/rclone"
REMOTE_HEARTBEAT = "gdrive:3SK_International/_Iris_Memory/Daily/.activity/heartbeat.json"

# ---- helpers -----------------------------------------------------------------
def fresh(p: Path, hours: float, now: float = None) -> bool:
    """File exists and was modified within the last N hours."""
    now = time.time() if now is None else now
    return p.is_file() and (now - p.stat().st_mtime) <= hours * 3600

# run_claude_job.sh's success sentinel. Anchored on "completed ok at" because
# "completed WITHOUT sentinel" also contains "completed" — and because the log's
# MTIME is worthless as a success signal: the wrapper tee's output during the run
# and appends a line on EVERY outcome (INCOMPLETE, AUTH/CREDIT FAILURE,
# INFRA-BLOCKED, STARTUP-ABORT), so an mtime check reports green on a night the
# job ran and failed. That really happened: nightly INCOMPLETE 7/16 and 7/18.
_SENTINEL = re.compile(
    r"run_claude_job: '(?P<job>[a-z0-9-]+)' completed ok at "
    r"(?P<ts>\d{4}-\d{2}-\d{2} \d{2}:\d{2})"
)

def completed_ok_within(log: Path, job: str, hours: float, now: datetime) -> bool:
    """The job's LAST clean-completion sentinel is within the last N hours."""
    try:
        text = log.read_text(errors="ignore")
    except OSError:
        return False
    last = None
    for m in _SENTINEL.finditer(text):
        if m.group("job") == job:
            last = m.group("ts")
    if last is None:
        return False
    ts = datetime.strptime(last, "%Y-%m-%d %H:%M").replace(tzinfo=ET)
    return timedelta(0) <= (now - ts) <= timedelta(hours=hours)

def last_occurrence(hour: int, now: datetime) -> datetime:
    """Most recent HH:00 ET at or before `now`."""
    t = now.replace(hour=hour, minute=0, second=0, microsecond=0)
    return t if t <= now else t - timedelta(days=1)

def briefing_ok(now: datetime, mtime: float = None) -> bool:
    """Directional floor: the briefing is at least as fresh as the last 08:00.

    A rolling window would false-alarm whenever this job itself fires late
    (machine asleep at 06:55); a floor treats fresher-than-expected as fine.
    """
    p = VAULT / "DAILY_BRIEFING.md"
    if mtime is None:
        if not p.is_file():
            return False
        mtime = p.stat().st_mtime
    floor = (last_occurrence(MORNING_BRIEFING_HOUR, now) - BRIEFING_GRACE).timestamp()
    return mtime >= floor

# ---- the six legs ------------------------------------------------------------
def build_checks(now: datetime):
    today = now.strftime("%Y-%m-%d")
    return {
        "activity_log": (
            lambda: (VAULT / "_Iris_Memory/Daily/.activity" / f"{today}.jsonl").stat().st_size > 0
            if (VAULT / "_Iris_Memory/Daily/.activity" / f"{today}.jsonl").is_file() else False,
            f".activity/{today}.jsonl exists and is non-empty",
        ),
        "daily_briefing": (
            lambda: briefing_ok(now),
            f"DAILY_BRIEFING.md at least as fresh as the last {MORNING_BRIEFING_HOUR:02d}:00 morning brief",
        ),
        "value_pulse_digest": (
            lambda: any((VAULT / "_Iris_Memory/Sessions").glob(f"{today}_*Nightly_Value_Pulse*.md")),
            f"Sessions/{today}_*_Nightly_Value_Pulse.md exists",
        ),
        "daily_note": (
            lambda: fresh(VAULT / "_Iris_Memory/Daily" / f"{today}.md", 12),
            f"Daily/{today}.md written overnight",
        ),
        "nightly_eng": (
            lambda: completed_ok_within(LOGS / "claude-code-nightly.log", "nightly", 12, now),
            "nightly job logged 'completed ok' within 12h (03:00 job)",
        ),
        "book_update": (
            lambda: completed_ok_within(LOGS / "claude-code-book-update.log", "book-update", 12, now),
            "book-update job logged 'completed ok' within 12h (02:30 job)",
        ),
    }

# ---- run ---------------------------------------------------------------------
def push_to_drive(today: str) -> dict:
    """Best-effort push. Runs strictly after the local write, so it can never
    corrupt the heartbeat. copyto (never sync) deletes nothing.

    Pushes TWICE: the stable heartbeat.json, plus a dated heartbeat-<date>.json.
    The dated copy is what makes staleness structurally undetectable-proof from
    this side — "today's file is absent on Drive" is unambiguous to ANY reader,
    so the watchdog catching a dark Mini no longer depends on it remembering to
    compare date_et before trusting all_green.

    The dated copies self-clean and need no retention job: they exist ONLY on
    Drive, so the 03:45 drive-sync vault mirror deletes yesterday's before this
    job pushes today's (verified by dry-run). That coupling is implicit — if
    `.activity/**` is ever added to drive-sync.excludes, they will accumulate
    here forever and want a real retention sweep.
    """
    if not Path(RCLONE).is_file():
        return {"ok": False, "error": f"rclone not found at {RCLONE}"}
    dated = REMOTE_HEARTBEAT.replace("heartbeat.json", f"heartbeat-{today}.json")
    for dest in (REMOTE_HEARTBEAT, dated):
        try:
            r = subprocess.run(
                [RCLONE, "copyto", str(HEARTBEAT), dest, "--log-level", "ERROR"],
                capture_output=True, text=True, timeout=120,
            )
            if r.returncode != 0:
                return {"ok": False, "error": f"{dest}: {(r.stderr or r.stdout or '').strip()[:250]}"}
        except Exception as exc:
            return {"ok": False, "error": f"{dest}: {exc!r}"}
    return {"ok": True}

def alert(msg: str) -> None:
    """Best-effort Telegram ping; never let a notify failure mask our exit."""
    try:
        subprocess.run([NOTIFY, msg], capture_output=True, timeout=30)
    except Exception:
        pass

def main() -> int:
    now = datetime.now(ET)
    legs, all_green = {}, True
    for name, (fn, expected) in build_checks(now).items():
        try:
            ok = bool(fn())
            legs[name] = {"ok": ok, "expected": expected}
        except Exception as exc:  # a check crashing is itself an anomaly
            ok = False
            legs[name] = {"ok": False, "expected": expected, "check_error": repr(exc)}
        all_green &= ok

    heartbeat = {
        "version": "1.3",
        "host": socket.gethostname(),
        "date_et": now.strftime("%Y-%m-%d"),
        "generated_at_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "generated_at_et": now.isoformat(timespec="seconds"),
        "all_green": all_green,
        "legs": legs,
    }

    # atomic write so the sync layer never ships a half-written file
    HEARTBEAT.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=HEARTBEAT.parent, suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as f:
            json.dump(heartbeat, f, indent=2)
        os.chmod(tmp, 0o644)  # mkstemp gives 0600; match the vault norm
        os.replace(tmp, HEARTBEAT)
    except Exception:
        Path(tmp).unlink(missing_ok=True)
        raise

    push = push_to_drive(heartbeat["date_et"])

    verdict = "ALL GREEN" if all_green else "ANOMALY"
    failed = [n for n, r in legs.items() if not r["ok"]]
    push_note = "" if push["ok"] else f" — DRIVE PUSH FAILED: {push.get('error')}"
    line = (f"[selfcheck {now:%H:%M}] {verdict}"
            + (f" — failed: {', '.join(failed)}" if failed else "")
            + push_note)
    print(line)

    if not (all_green and push["ok"]):
        alert(f"🟠 overnight selfcheck {now:%m-%d %H:%M}: {verdict}"
              + (f" — failed legs: {', '.join(failed)}" if failed else "")
              + push_note)
        return 1
    return 0

# ---- selftest ----------------------------------------------------------------
def selftest() -> int:
    """The date logic + sentinel parsing are the parts that can rot silently."""
    d = lambda s: datetime.strptime(s, "%Y-%m-%d %H:%M").replace(tzinfo=ET)
    checks = [0]

    def ck(cond, msg):
        assert cond, msg
        checks[0] += 1

    # last_occurrence
    ck(last_occurrence(8, d("2026-07-22 06:55")) == d("2026-07-21 08:00"), "before 08:00 -> yesterday")
    ck(last_occurrence(8, d("2026-07-22 09:55")) == d("2026-07-22 08:00"), "after 08:00 -> today")
    ck(last_occurrence(8, d("2026-07-22 08:00")) == d("2026-07-22 08:00"), "exactly 08:00 -> today")

    # briefing floor at the normal 06:55 fire: yesterday's 08:02 regen passes,
    # the day before's does not.
    now = d("2026-07-22 06:55")
    ck(briefing_ok(now, d("2026-07-21 08:02").timestamp()), "yesterday's brief is current at 06:55")
    ck(not briefing_ok(now, d("2026-07-20 08:02").timestamp()), "two-day-old brief must fail")

    # late fire after a machine sleep must NOT invent a failure (the bug a
    # rolling 26h window would have had)
    late = d("2026-07-22 09:55")
    ck(briefing_ok(late, d("2026-07-22 08:02").timestamp()), "late fire, fresh brief -> ok")
    ck(not briefing_ok(late, d("2026-07-21 08:02").timestamp()), "late fire, missing regen -> fail")

    # grace absorbs an early/jittery regen
    ck(briefing_ok(now, d("2026-07-21 06:30").timestamp()), "2h grace absorbs an early regen")
    ck(not briefing_ok(now, d("2026-07-21 05:30").timestamp()), "beyond grace -> fail")

    # fresh(): the mtime helper the daily_note leg rests on
    with tempfile.NamedTemporaryFile(suffix=".probe") as tf:
        p, t = Path(tf.name), time.time()
        ck(fresh(p, 12, now=t), "just-written file is fresh")
        ck(not fresh(p, 12, now=t + 13 * 3600), "13h-old file is not fresh within 12h")
        ck(not fresh(Path("/nonexistent/nope.md"), 12), "missing file is never fresh")

    # completed_ok_within(): the sentinel parse both job legs rest on. The whole
    # point is that a FAILED run must not read as green even though the wrapper
    # appended to the log (nightly INCOMPLETE 7/16 + 7/18 would have).
    with tempfile.TemporaryDirectory() as td:
        log = Path(td) / "probe.log"
        ck(not completed_ok_within(log, "nightly", 12, now), "missing log -> red")
        log.write_text("run_claude_job: 'nightly' INCOMPLETE at 2026-07-22 03:01 EDT\n")
        ck(not completed_ok_within(log, "nightly", 12, now), "INCOMPLETE must NOT read as green")
        log.write_text("run_claude_job: 'nightly' completed WITHOUT sentinel at 2026-07-22 03:01 EDT\n")
        ck(not completed_ok_within(log, "nightly", 12, now), "'completed WITHOUT sentinel' must NOT match")
        log.write_text("run_claude_job: 'nightly' completed ok at 2026-07-22 03:01 EDT\n")
        ck(completed_ok_within(log, "nightly", 12, now), "clean completion within 12h -> green")
        ck(not completed_ok_within(log, "book-update", 12, now), "another job's sentinel must not count")
        log.write_text("run_claude_job: 'nightly' completed ok at 2026-07-21 03:01 EDT\n")
        ck(not completed_ok_within(log, "nightly", 12, now), "yesterday's completion -> red (job died)")
        # last sentinel wins: a clean run followed by a failed one is NOT green
        log.write_text("run_claude_job: 'nightly' completed ok at 2026-07-22 03:01 EDT\n"
                       "run_claude_job: 'nightly' completed ok at 2026-07-20 03:01 EDT\n")
        ck(not completed_ok_within(log, "nightly", 12, now), "LAST sentinel wins, not the newest")

    # every leg must be evaluable without throwing
    for name, (fn, _) in build_checks(now).items():
        fn()
        checks[0] += 1

    print(f"selftest: {checks[0]}/{checks[0]} PASS")
    return 0

if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--selftest", action="store_true", help="run date-logic checks and exit")
    args = ap.parse_args()
    if args.selftest:
        # deliberately OUTSIDE the alert-wrapping try: a failing assertion during
        # a dev run must not page Steve's Telegram.
        sys.exit(selftest())
    try:
        sys.exit(main())
    except Exception as exc:
        print(f"[selfcheck] SELF-ERROR: {exc!r}", file=sys.stderr)
        alert(f"🔴 overnight selfcheck SELF-ERROR: {exc!r}")
        sys.exit(2)
